# Chapter 6 - NUMPY OPERATIONS

## Arithmetic Functions

In [19]:
import numpy as np

In [22]:
## np.add(arr1,arr2)
a1 = np.array([[1, 2, 3, 4, 5], [6, 8, 3, 8, 10]])
a2 = np.array([[3, 8, 3, 1, 10],[1, 2, 3, 4, 5]])

print(np.add(a1,a2))

[[ 4 10  6  5 15]
 [ 7 10  6 12 15]]


In [24]:
## np.subtract(arr1,arr2)
a3 = np.arange(5, 15, 2)
a4 = np.arange(1, 11, 2)

print(a3)
print(a4)
print(np.subtract(a3,a4))

[ 5  7  9 11 13]
[1 3 5 7 9]
[4 4 4 4 4]


In [26]:
## np.multiply(arr1,arr2)
a3 = np.arange(5, 15, 2)
a4 = np.arange(1, 11, 2)

print(a3)
print(a4)
print(np.multiply(a3,a4))

[ 5  7  9 11 13]
[1 3 5 7 9]
[  5  21  45  77 117]


In [27]:
## np.divide(arr1,arr2)
a1 = np.array([[1, 2, 3, 4, 5], [6, 8, 3, 8, 10]])
a2 = np.array([[3, 8, 3, 1, 10],[1, 2, 3, 4, 5]])

print(np.divide(a1,a2))

[[0.33333333 0.25       1.         4.         0.5       ]
 [6.         4.         1.         2.         2.        ]]


In [28]:
## np.mod(arr1,arr2)
a5 = np.array([10,24,67])
a6 = np.array([2,10,5])

print(np.mod(a5,a6))

[0 4 2]


In [29]:
## np.remainder(arr1,arr2)

a5 = np.array([10,24,67])
a6 = np.array([2,10,5])

print(np.remainder(a5,a6))

[0 4 2]


In [30]:
## np.power(arr1,value)

a6 = np.array([2,10,5])

print(np.power(a6, 2))

[  4 100  25]


In [31]:
## np.sqrt(arr1)

a7 = np.array([2,9,64])

print(np.sqrt(a6))

[1.41421356 3.16227766 2.23606798]


In [32]:
## np.absolute(arr1)

a8 = np.array([-2,0,-64])
print(np.absolute(a8))

[ 2  0 64]


## Aggregation Functions

In [33]:
## np.sum(arr)
a7 = np.array([2,9,64])
print(np.sum(a7))

75


In [35]:
## np.sum([arr1,arr2])
a7 = np.array([2,9,64])
a8 = np.array([-2,0,-64])

## [a7,a8] = np.array([2,9,64,-2,0,-64 ])
print(np.sum([a7,a8]))


9


In [36]:
print(np.sum(a7,a8))

TypeError: only integer scalar arrays can be converted to a scalar index

In [39]:
## np.prod(arr)
a9 = np.array([2,9,6])
print(np.prod(a9))

108


In [38]:
## np.prod([arr1,arr2])

a9 = np.array([2,9,6])
a10 = np.array([-2,5,3])

print(np.prod([a9,a10]))

-3240


In [40]:
## np.min(arr)
a10 = np.array([-2,5,3])
print(np.min(a10))

-2


In [41]:
## np.max(arr)
a10 = np.array([-2,5,3])
print(np.max(a10))

5


In [42]:
## np.mean(arr)
a10 = np.array([-2,5,3])
print(np.mean(a10))

2.0


In [45]:
## np.median(arr)

a10 = np.array([6,7,3])
print(np.mean(a10))

5.333333333333333


In [46]:
## np.std(arr)

a10 = np.array([6,7,3])
print(np.std(a10))

1.699673171197595


In [47]:
## np.var(arr)

a10 = np.array([6,7,3])
print(np.var(a10))

2.888888888888889


## Exceptions! Element-Wise Operations

In [ ]:
## np.sum(arr1,arr2)

In [49]:
## np.sum([arr1,arr2], axis=0)

a7 = np.array([2,9,64])
a8 = np.array([-2,0,-64])

print(np.sum([a7,a8], axis=0))

[0 9 0]


In [50]:
## np.sum([arr1,arr2], axis=1)

a7 = np.array([2,9,64])
a8 = np.array([-2,0,-64])

print(np.sum([a7,a8], axis=1))

[ 75 -66]


In [53]:
## np.prod(arr1,arr2)
print(np.prod(a11,a12))

TypeError: only integer scalar arrays can be converted to a scalar index

In [52]:
## np.prod([arr1,arr2], axis=0)

a11 = np.array([2,1,5])
a12 = np.array([10,3,2])

print(np.prod([a11,a12], axis=0))

[20  3 10]


In [54]:
## np.prod([arr1,arr2], axis=1)

a11 = np.array([2,1,5])
a12 = np.array([10,3,2])

print(np.prod([a11,a12], axis=1))

[10 60]


## Matrix Manipulations

In [57]:
## np.dot(arr,value)

x = np.array([[1., 2., 3.], [4., 5., 6.]])

print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [58]:
print(np.dot(x, 2))

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [ ]:
## np.dot(arr1,arr2)  ## arr1 =[M✖N] , arr2 = [N✖K]  ->    np.dot(arr1,arr2) = [M✖K]

In [59]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x.shape, y.shape)

print(np.dot(x,y))

(2, 3) (3, 2)
[[ 28.  64.]
 [ 67. 181.]]


In [62]:
## arr.transpose()

y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(y)
print(y.shape)

print(y.transpose())

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
(3, 2)
[[ 6. -1.  8.]
 [23.  7.  9.]]


In [63]:
## arr.flatten()

y = np.array([[6., 23.], [-1, 7], [8, 9]]) # 2D array

print(y.flatten())

[ 6. 23. -1.  7.  8.  9.]


In [67]:
c3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(c3.flatten())

temp = c3.flatten()
print(temp.shape)

[1 2 3 4 5 6 7 8]
(8,)


In [76]:
## np.hstack(arr1,arr2) # Concatenate horizontally

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23., 9], [-1, 7, 8]])

print(np.hstack((x,y)))

[[ 1.  2.  3.  6. 23.  9.]
 [ 4.  5.  6. -1.  7.  8.]]


In [77]:
## np.vstack(arr1,arr2) # Concatenate vertically

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23., 9], [-1, 7, 8]])

print(np.vstack((x,y)))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 6. 23.  9.]
 [-1.  7.  8.]]
