### Numpy Indexing

In [1]:
import numpy as np

### 1D Array

In [4]:
arr = np.array([56,83,12,34,90], dtype=np.int32)
print(arr)

[56 83 12 34 90]


In [7]:
print(arr[2])

12


In [8]:
print(arr[0])

56


In [9]:
print(arr[4])

90


### 2D Array

In [10]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
print(arr2[0,1])

2


In [13]:
print(arr2[1,2])

6


In [14]:
arr2 = np.array([['q','h'],['a','b']])

In [16]:
print(arr2[0,0])

q


### 3D Array

In [19]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [22]:
print(arr3[0,0,1])

2


In [23]:
print(arr3[0,2,0])

7


### Negative Indexing

In [25]:
arr = np.array([56,83,12,34,90])
print(arr[-1])

90


In [26]:
print(arr[-3])

12


In [27]:

print(arr2[0,-1])

h


In [28]:
print(arr2[1,-2])

a


In [29]:
print(arr2[1,0])

a


### Fancy Indexing

In [31]:
arr = np.array([56,83,12,34,90])
indexed = [0,2,3]
print(arr[indexed])

[56 12 34]


In [32]:
print(arr[0,2,3])

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [33]:
arr = np.array([56,83,12,34,90])
indexed2 = [3,4]
print(arr[indexed2])

[34 90]


### Boolean Indexing

In [34]:
arr = np.array([56,83,12,34,90])
cond = arr > 30
print(arr[cond])

[56 83 34 90]


In [35]:
arr = np.array([56,83,12,34,90])
cond1 = arr < 30
print(arr[cond1])

[12]
