In [1]:
import numpy as np

In [2]:
# create a 0D Array
arr0 = np.array(56)

In [3]:
print(arr1)

56


In [4]:
# create a 1D Array
arr1 = np.array([4,7,3,5])

In [5]:
print(arr1)

[4 7 3 5]


In [6]:
# create a 2D Array
arr2 = np.array([[100,200,300],[10,20,30]])
print(arr2)

[[100 200 300]
 [ 10  20  30]]


In [8]:
# create a 3D Array
arr3 = np.array([[[1,2],[3,4],[5,6]]])
print(arr3)

[[[1 2]
  [3 4]
  [5 6]]]


In [21]:
arr3new = np.array([[[1,2,8],[1,2,5],[1,2,3],[1,3,2]]])
print(arr3new)

[[[1 2 8]
  [1 2 5]
  [1 2 3]
  [1 3 2]]]


In [22]:
print(arr3new.shape)

(1, 4, 3)


In [25]:
print(arr1.size)

4


In [28]:
print(arr3.dtype)

int64


In [34]:
arrstr = np.array(['a','d','xhugde'])
print(arrstr)

['a' 'd' 'xhugde']


In [35]:
print(arrstr.dtype)

<U6


In [42]:
print(arrstr.ndim)

1


In [57]:
arr1 = np.array([4,7,3,5])

In [58]:
print(arr1.shape)

(4,)


In [68]:
arr1_reshape = arr1.reshape(1,4,1)
print(arr1_reshape)

[[[4]
  [7]
  [3]
  [5]]]


In [69]:
print(arr1_reshape.shape)

(1, 4, 1)


In [70]:
arr3 = np.array([[[1,2],[3,4],[5,6]]])
print(arr3)

[[[1 2]
  [3 4]
  [5 6]]]


In [72]:
arr3_res = arr3.reshape(3,2)
print(arr3_res)

[[1 2]
 [3 4]
 [5 6]]
