In [1]:
import numpy as np

## Slicing For 1D Array

In [2]:
arr1 = np.array([4,5,6,7,8,9])

print(arr1[2:5])

[6 7 8]


In [3]:
print(arr1[0:2])

[4 5]


In [4]:
print(arr1[1:4])

[5 6 7]


In [5]:
print(arr1[1:])

[5 6 7 8 9]


In [6]:
print(arr1[:3])

[4 5 6]


## Negative Slicing

In [7]:
arr1 = np.array([4,5,6,7,8,9])

print(arr1[-3:-1])

[7 8]


In [8]:
print(arr1[-3:])

[7 8 9]


In [14]:
print(arr1[0:5:3])

[4 7]


## Slicing For 2D Array

In [17]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [18]:
print(arr2[0, 1:])

[2 3]


In [19]:
print(arr2[0, 0:2])

[1 2]


In [20]:
print(arr2[0:2, 0:2])

[[1 2]
 [4 5]]


In [21]:
print(arr2[0:2, 1:])

[[2 3]
 [5 6]]


In [22]:
print(arr2[0:2, 2])

[3 6]


In [41]:
arr1 = np.array([4,5,6,7,8,9])
print(arr1[::-1])

[9 8 7 6 5 4]
