## Numpy Search

In [13]:
import numpy as np

### where()

In [14]:
arr = np.array([4, 2, 3, 4, 5, 4, 3])

# search in the array and return the index of the element
res = np.where(arr == 4)

print(res)

(array([0, 3, 5]),)


In [15]:
arr = np.array([4, 2, 3, 4, 5, 4, 3])

# search in the array and return the index of the element
res = np.where(arr == 3)

print(res)

(array([2, 6]),)


In [16]:
arr = np.array([4, 2, 3, 4, 5, 4, 3])

# search in the array and return the index of the element
res = np.where(arr == 2)

print(res)

(array([1]),)


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

res = np.where(arr >=4)

print(res)

(array([3, 4, 5, 6, 7]),)


In [18]:
# 2D array
arr = np.array([[1, 8, 3, 4], [5, 6, 7, 8]])

res = np.where(arr == 8)

print(res)

(array([0, 1]), array([1, 3]))


### searchsorted()

In [25]:
arr = np.array([6, 7, 8, 9])

res = np.searchsorted(arr, 8)

print(res)

2


In [26]:
arr = np.array([6, 7, 8, 9])

res = np.searchsorted(arr, 10)

print(res)

4


In [27]:
arr = [1, 2, 2, 3, 3, 3, 4, 5, 6, 6] 
print(arr) 
  
# left-most 4 
print("left-most index") 
print(np.searchsorted(arr, 4, side="left"))   

[1, 2, 2, 3, 3, 3, 4, 5, 6, 6]
left-most index
6


In [28]:
arr = [1, 2, 2, 3, 3, 3, 4, 5, 6, 6] ## sorted from right = [6,6,5,4,3,3,3,2,2,1]
print(arr) 

# right-most 4 
print("right-most index")
print(np.searchsorted(arr, 4, side="right"))

[1, 2, 2, 3, 3, 3, 4, 5, 6, 6]
right-most index
7


In [32]:
arr = np.array([6, 7, 8, 9]) ## sorted from right = [9,8,7,6]

x = np.searchsorted(arr, 7, side='right')

print(x)


2


In [33]:
arr = np.array([1, 3, 5, 7]) 

# search multiple values
res = np.searchsorted(arr, [2, 4, 6])  ## arr = [1,2,3,4,5,6,7]

print(res)

[1 2 3]


## Numpy Sort

In [10]:
import numpy as np

### sort()

In [34]:
arr = np.array([3, 2, 0, 1])
# sort the array without changing the original array
print(np.sort(arr))
print(arr)

[0 1 2 3]
[3 2 0 1]


In [35]:
arr = np.array(['red', 'White', 'blue', 'white', 'brown'])

print(np.sort(arr))

['White' 'blue' 'brown' 'red' 'white']


In [36]:
arr = np.array([True, False, True, False])

print(np.sort(arr))

[False False  True  True]


In [37]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

# 2d Array sort
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [38]:
# sort along the first axis
a = np.array([[8, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)        
print ("Sort along column axis : \n", arr1)        

Sort along column axis : 
 [[ 8  1]
 [10 15]]


In [39]:
# sort along the last axis
a = np.array([[15, 10], [12, 1]])
arr2 = np.sort(a, axis = -1)        
print ("Sort along row axis : \n", arr2)

Sort along row axis : 
 [[10 15]
 [ 1 12]]


In [40]:
 a = np.array([[15, 10], [10, 1]])
arr3 = np.sort(a, axis = None)        
print ("General sort : \n", arr3)

General sort : 
 [ 1 10 10 15]
